### ISSUE TITLE
Theme overhaul/replacement

### ISSUE THREAD

**Issue by tmhmitchell** [pisoc/pisoc.net#23]
We'd like a few extra features out of the theme. Content published on the site should now include:

-  News
- Projects
- Exec Meeting minutes (could come under news?)
- Random/things

Some design considerations:

- I'd like to propose we display things differently on the main page - instead of "stacked", the "latest" of each section could be displayed in horizontal columns, to use up some of the white space. 
- Have links for "session/event schedules", perhaps based on a google calender?
- a "pinned" article/s, such as latest upcoming event/s - so that we can post new news, but "unimportant", non-time sensitive things don't bump "public" news like events. 

One thing we should consider is if it's worth modifying our current theme to achieve these things (doable... I think?) or finding a new theme closer to our needs

**Comment by Akryllyk** [comment]
https://themes.gohugo.io/hugo-theme-hello-friend-ng/

https://themes.gohugo.io/hermit/

**Comment by tmhmitchell** [comment]
https://themes.gohugo.io/hugo-theme-pure/ - with some customisation (also a dark theme!), this could be quite nice

**Comment by Akryllyk** [comment]
most of this has now been done.

TODO:
pinned articles
Calendar type thing

**Comment by tmhmitchell** [comment]
Pinned sessions done - calender type thing to be put off until sessions structure is decided
