### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by tmhmitchell** [pisoc/pisoc.net#9]
My eyes ow

**Comment by Akryllyk** [comment]
https://radu-matei.com/blog/dark-mode/

May be useful idk

**Comment by tmhmitchell** [comment]
After some discussion:
1. Create a dark-mode stylesheet that implements switched colours
2. Use JS to enable/disable said stylesheet (https://stackoverflow.com/questions/14292997/changing-style-sheet-javascript)
